name: build-windows
on:
  workflow_dispatch: null
  push:
    branches: [main]

jobs:
  build-windows:
    name: Build StemRoller for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm i -D
      - run: npm run download-third-party-apps
      - run: npm run build:win
      - uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
      - run: Rename-Item dist\win-unpacked -NewName stemroller-${{ steps.package-version.outputs.version }}-win-cuda
      - run: Invoke-WebRequest -Uri https://www.7-zip.org/a/7zr.exe -OutFile 7zr.exe
      - run: Invoke-WebRequest -Uri https://www.7-zip.org/a/7z2201-x64.exe -OutFile 7zInstaller-x64.exe
      - run: .\7zr.exe x "7zInstaller-x64.exe"
      - run: move "dist\stemroller-${{ steps.package-version.outputs.version }}-win-cuda" "stemroller-${{ steps.package-version.outputs.version }}-win-cuda"
      - run: .\7z.exe a -m0=lzma2 -mmt=on -mx=9 -sfx"7z.sfx" "stemroller-${{ steps.package-version.outputs.version }}-win-cuda.exe" "stemroller-${{ steps.package-version.outputs.version }}-win-cuda"
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package-version.outputs.version }}
          files: stemroller-${{ steps.package-version.outputs.version }}-win-cuda.exe
